DROP TABLE ALLOCATION         CASCADE CONSTRAINTS PURGE;
DROP TABLE APPLICATION        CASCADE CONSTRAINTS PURGE;
DROP TABLE SCHOLARSHIP_PROGRAM CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT            CASCADE CONSTRAINTS PURGE;
DROP TABLE DEPARTMENT         CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS              CASCADE CONSTRAINTS PURGE;

CREATE TABLE USERS (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR2(20)     NOT NULL,
    name          VARCHAR2(150)    NOT NULL,
    password      VARCHAR2(255)    NOT NULL,
    role          VARCHAR2(10)     NOT NULL,
    CONSTRAINT pk_users          PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role     CHECK (role IN ('ADMIN','STUDENT'))
);

CREATE TABLE DEPARTMENT (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR2(150) NOT NULL,
    dept_code     VARCHAR2(2)   NOT NULL,
    capacity      NUMBER        NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uq_dept_code  UNIQUE (dept_code),
    CONSTRAINT ck_dept_cap   CHECK (capacity > 0)
);

CREATE TABLE STUDENT (
    student_id    NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       NUMBER        NOT NULL,
    department_id NUMBER        NOT NULL,
    roll_number   NUMBER        NOT NULL,
    gender        VARCHAR2(10)  NOT NULL,
    cgpa          NUMBER(4,2)   NOT NULL,
    family_income NUMBER(15,2)  NOT NULL,
    semester      NUMBER(2)     NOT NULL,
    CONSTRAINT pk_student        PRIMARY KEY (student_id),
    CONSTRAINT uq_student_roll   UNIQUE (roll_number),
    CONSTRAINT uq_student_user   UNIQUE (user_id),
    CONSTRAINT fk_student_user   FOREIGN KEY (user_id)        REFERENCES USERS(user_id),
    CONSTRAINT fk_student_dept   FOREIGN KEY (department_id)  REFERENCES DEPARTMENT(department_id),
    CONSTRAINT ck_student_gender CHECK (gender IN ('male','female')),
    CONSTRAINT ck_student_cgpa   CHECK (cgpa BETWEEN 0 AND 4),
    CONSTRAINT ck_student_sem    CHECK (semester BETWEEN 1 AND 12)
);

CREATE TABLE SCHOLARSHIP_PROGRAM (
    scholarship_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by     NUMBER        NOT NULL,
    department_id  NUMBER,
    title          VARCHAR2(255) NOT NULL,
    description    VARCHAR2(1000),
    amount         NUMBER(15,2)  NOT NULL,
    slots          NUMBER        NOT NULL,
    min_cgpa       NUMBER(4,2),
    max_income     NUMBER(15,2),
    deadline       DATE          NOT NULL,
    application_required       NUMBER(1) DEFAULT 1 NOT NULL,
    gender_requirement         VARCHAR2(10),
    allow_existing_scholarship NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_scholarship      PRIMARY KEY (scholarship_id),
    CONSTRAINT fk_sch_created_by   FOREIGN KEY (created_by)    REFERENCES USERS(user_id),
    CONSTRAINT fk_sch_dept         FOREIGN KEY (department_id) REFERENCES DEPARTMENT(department_id),
    CONSTRAINT ck_sch_gender       CHECK (gender_requirement IN ('male','female'))
);

CREATE TABLE APPLICATION (
    application_id  NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id      NUMBER      NOT NULL,
    scholarship_id  NUMBER      NOT NULL,
    applied_at      DATE        DEFAULT SYSDATE,
    merit_score     NUMBER(5,2),
    CONSTRAINT pk_application      PRIMARY KEY (application_id),
    CONSTRAINT uq_app_student_sch  UNIQUE (student_id, scholarship_id),
    CONSTRAINT fk_app_student      FOREIGN KEY (student_id)     REFERENCES STUDENT(student_id),
    CONSTRAINT fk_app_scholarship  FOREIGN KEY (scholarship_id) REFERENCES SCHOLARSHIP_PROGRAM(scholarship_id)
);

PROMPT Schema created successfully.

-- ============================================================
-- Simplified Views (No Allocation / No Status Logic)
-- ============================================================

CREATE OR REPLACE VIEW V_SCHOLARSHIP_SUMMARY AS
SELECT
    sp.scholarship_id,
    sp.title,
    NVL(d.name, 'All Departments')   AS department_name,
    sp.department_id,
    sp.slots                          AS recipient_count,
    sp.application_required,
    sp.min_cgpa,
    sp.max_income                     AS max_family_income,
    sp.gender_requirement,
    sp.allow_existing_scholarship,
    sp.description,
    sp.amount,
    sp.deadline,
    u.name                            AS created_by_name,
    sp.created_by,
    agg.total_applications
FROM
    SCHOLARSHIP_PROGRAM sp
    LEFT JOIN DEPARTMENT  d  ON d.department_id  = sp.department_id
    LEFT JOIN USERS        u  ON u.user_id        = sp.created_by
    LEFT JOIN (
        SELECT
            scholarship_id,
            COUNT(*) AS total_applications
        FROM APPLICATION
        GROUP BY scholarship_id
    ) agg ON agg.scholarship_id = sp.scholarship_id;

CREATE OR REPLACE VIEW V_STUDENT_APPLICATIONS AS
SELECT
    a.application_id,
    a.student_id,
    a.scholarship_id,
    a.applied_at                      AS application_date,
    a.merit_score,
    -- Student info
    u.name                            AS student_name,
    s.roll_number,
    s.gender,
    s.cgpa,
    s.family_income,
    s.semester,
    -- Department info
    d.name                            AS department_name,
    d.dept_code,
    -- Scholarship info
    sp.title                          AS scholarship_title,
    NVL(sd.name, 'All Departments')   AS scholarship_dept_name,
    sp.slots                          AS recipient_count,
    sp.application_required,
    sp.min_cgpa                       AS scholarship_min_cgpa,
    sp.max_income                     AS scholarship_max_income,
    sp.gender_requirement             AS scholarship_gender_req
FROM
    APPLICATION          a
    JOIN STUDENT         s   ON s.student_id    = a.student_id
    JOIN USERS            u   ON u.user_id       = s.user_id
    JOIN DEPARTMENT       d   ON d.department_id = s.department_id
    JOIN SCHOLARSHIP_PROGRAM sp ON sp.scholarship_id = a.scholarship_id
    LEFT JOIN DEPARTMENT  sd  ON sd.department_id = sp.department_id;

PROMPT Views created successfully.
